### ISSUE TITLE
ImportError: cannot import name '_uuid_generate_random'

### ISSUE THREAD

**Issue by bangq** [ifwenvlook/blog#3]
你好，报这个错误，帮忙看下
Traceback (most recent call last):
  File "c:\users\sanli\appdata\local\programs\python\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\sanli\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\sanli\AppData\Local\Programs\Python\Python35\Scripts\celery.exe\__main__.py", line 5, in <module>
  File "c:\users\sanli\appdata\local\programs\python\python35\lib\site-packages\celery\__init__.py", line 130, in <modul
e>
    from celery import five
  File "c:\users\sanli\appdata\local\programs\python\python35\lib\site-packages\celery\five.py", line 149, in <module>
    from kombu.utils.compat import OrderedDict  # noqa
  File "c:\users\sanli\appdata\local\programs\python\python35\lib\site-packages\kombu\utils\__init__.py", line 19, in <m
odule>
    from uuid import UUID, uuid4 as _uuid4, _uuid_generate_random
ImportError: cannot import name '_uuid_generate_random'

**Comment by arkilis** [comment]
最好用 python3来运行
