### ISSUE TITLE
ImportError: cannot import name '_uuid_generate_random',请问这是什么原因？

### ISSUE THREAD

**Issue by feixianghs** [ifwenvlook/blog#6]
```
Traceback (most recent call last):
  File "manage.py", line 17, in <module>
    from app import create_app, db
  File "/Users/saifeihu/Desktop/blog-master/app/__init__.py", line 9, in <module>
    from celery import Celery
  File "/Users/saifeihu/Desktop/blog-master/blog/lib/python3.6/site-packages/celery/__init__.py", line 130, in <module>
    from celery import five
  File "/Users/saifeihu/Desktop/blog-master/blog/lib/python3.6/site-packages/celery/five.py", line 149, in <module>
    from kombu.utils.compat import OrderedDict  # noqa
  File "/Users/saifeihu/Desktop/blog-master/blog/lib/python3.6/site-packages/kombu/utils/__init__.py", line 19, in <module>
    from uuid import UUID, uuid4 as _uuid4, _uuid_generate_random
ImportError: cannot import name '_uuid_generate_random'
```

**Comment by ifwenvlook** [comment]
没碰到过，参考以下答案
https://stackoverflow.com/questions/34198538/cannot-import-name-uuid-generate-random-in-heroku-django
